name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.19.0
      uses: actions/setup-node@v4
      with:
        node-version: '20.19.0'
        cache: 'pnpm'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Validate Node.js version
      run: node -v

    - name: Validate pnpm installation
      run: pnpm -v

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Run tests
      run: pnpm test:run